server:
#  port: 9090
  compression: 
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
#    url: jdbc:mysql://192.168.1.92:3306/keep?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    password: T_dl123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: gzz123
